spring.application.name=realestatebot


spring.thymeleaf.cache=false


# ======================================
# SERVER SETTINGS
# ======================================
server.port=8080

# ======================================
# POSTGRESQL SETTINGS
# ======================================
spring.datasource.url=jdbc:postgresql://localhost:5432/realbot
spring.datasource.username=realbot_user
spring.datasource.password=1998




# Hibernate auto create/update tables
spring.jpa.hibernate.ddl-auto=update

# Show SQL in logs (good for debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ======================================
# LOGGING SETTINGS (simple + powerful)
# ======================================
# Root logging level (DEBUG gives detailed output)
logging.level.root=INFO

# Log SQL Queries
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Log incoming HTTP requests
logging.level.org.springframework.web=DEBUG

# Log your project packages
logging.level.com.risingbee.realestate.realstatebot=DEBUG

# Pretty JSON logs (optional)
# spring.jackson.serialization.indent_output=true

# ======================================
# WHATSAPP CONFIG (fill later)
# ======================================
#whatsapp.verify-token=YOUR_VERIFY_TOKEN
#whatsapp.access-token=YOUR_ACCESS_TOKEN
#whatsapp.phone-number-id=YOUR_PHONE_NUMBER_ID



whatsapp.verify-token=12345
whatsapp.access-token=EAAQvJkpzFHMBQSlOHqlSi27j5u4lpLJ6BYrAJT7xQdr21CeWmTLQDSn1h7pCfZAeS5lN3OeZAfC6EzWxqCRyWgci0noUOFD9E1nSZBUF8jcJbO7Lg461LK3RRobl6iH82YR7X1LZBbmgqJbxfsMZB78ki1feGo0XRhPsZCBQuuUH3NiinnsjT9SJ9NaXewEf1RdajWIxzPC0hA1rf4Y1RkmcChrBFIngwZAGIN8SBUQR7SBS7kBZAupSP2UNVRcNq2gILZBuMJgB2VzudRLoRpqwksARI
whatsapp.phone-number-id=113410935050368
