spring.application.name=realestatebot


spring.thymeleaf.cache=false


# ======================================
# SERVER SETTINGS
# ======================================
server.port=8080

# ======================================
# POSTGRESQL SETTINGS
# ======================================
spring.datasource.url=jdbc:postgresql://localhost:5432/realbot
spring.datasource.username=realbot_user
spring.datasource.password=1998




# Hibernate auto create/update tables
spring.jpa.hibernate.ddl-auto=update

# Show SQL in logs (good for debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ======================================
# LOGGING SETTINGS (simple + powerful)
# ======================================
# Root logging level (DEBUG gives detailed output)
logging.level.root=INFO

# Log SQL Queries
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Log incoming HTTP requests
logging.level.org.springframework.web=DEBUG

# Log your project packages
logging.level.com.risingbee.realestate.realstatebot=DEBUG

# Pretty JSON logs (optional)
# spring.jackson.serialization.indent_output=true

# ======================================
# WHATSAPP CONFIG (fill later)
# ======================================
#whatsapp.verify-token=YOUR_VERIFY_TOKEN
#whatsapp.access-token=YOUR_ACCESS_TOKEN
#whatsapp.phone-number-id=YOUR_PHONE_NUMBER_ID



whatsapp.verify-token=12345
whatsapp.access-token=EAAhEbUHhZAu0BQJRQvnKZC8CvU9aXbt94SnlqNNNdGouPEg3LOfGH7n1q1Vd6F0IrSb2bBAq732uEvZAeiIUKdL3Bt0iQXOnoKrvJBsHf9UxTsp2mjbZCg90ibVPp3mh9VMVKISFxFrIGro7YmthjPmqSrkBFvMrPta3RnJMlUrwnJsh6lNsN7EBgDRANhsMdV6hkkQaGi1aIYW2OctiCTZCAqqsWSK4CzNw150z4gZBvODgem2SBR3AuMZAytxNoSc9QOEQ1G7yBQmlZCdXzp2fgOf3xQZDZD
whatsapp.phone-number-id=113410935050368
