spring.application.name=realestatebot


spring.thymeleaf.cache=false


# ======================================
# SERVER SETTINGS
# ======================================
server.port=8080

# ======================================
# POSTGRESQL SETTINGS
# ======================================
spring.datasource.url=jdbc:postgresql://localhost:5432/realbot
spring.datasource.username=realbot_user
spring.datasource.password=1998




# Hibernate auto create/update tables
spring.jpa.hibernate.ddl-auto=update

# Show SQL in logs (good for debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ======================================
# LOGGING SETTINGS (simple + powerful)
# ======================================
# Root logging level (DEBUG gives detailed output)
logging.level.root=INFO

# Log SQL Queries
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Log incoming HTTP requests
logging.level.org.springframework.web=DEBUG

# Log your project packages
logging.level.com.risingbee.realestate.realstatebot=DEBUG

# Pretty JSON logs (optional)
# spring.jackson.serialization.indent_output=true


# static configurations
spring.web.resources.static-locations=file:/home/ironman/Devlopment/realestatebot/

# multipart configs
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=30MB



# ======================================
# WHATSAPP CONFIG (fill later)
# ======================================
#whatsapp.verify-token=YOUR_VERIFY_TOKEN
#whatsapp.access-token=YOUR_ACCESS_TOKEN
#whatsapp.phone-number-id=YOUR_PHONE_NUMBER_ID






whatsapp.verify-token=12345
whatsapp.access-token=EAAQvJkpzFHMBQhuOZAVvXPUhgUST1zZCccfsZC1IjxX9cnKQj5IAH5ylbaDXY1SYFJ3OczTD0yKwPXVhoJJtvu52FZBSbXeYYX6opePZBZB0zptwiwnSkOyROxzL2qOKnGw8VM0tTbgo3WxTVZA7YWIFcErkbNYJ4MMgZCIcm0MTthaOVdrnqOUsMwoE9rP1OVfAwIthJa8uoCLuOur8OkQQVMx92MmSWYvb6x9edlcIDJgjO8QoQPXIPoXZB1zWu0zEvQIZA5YnZBbo0sQZA0PtQcDBghv9
whatsapp.phone-number-id=113410935050368
